before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: s3-webhook-dumper
    ldflags:
      - -s -w
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
checksum:
  name_template: 'checksums.txt'
dockers:
  - dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--pull"
    image_templates:
      - "ghcr.io/zebbra/s3-webhook-dumper:{{ .Tag }}-amd64"
      - "quay.io/zebbra/s3-webhook-dumper:{{ .Tag }}-amd64"
    goos: linux
    goarch: amd64
    ids:
      - s3-webhook-dumper
  - dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--pull"
    image_templates:
      - "ghcr.io/zebbra/s3-webhook-dumper:{{ .Tag }}-arm64"
      - "quay.io/zebbra/s3-webhook-dumper:{{ .Tag }}-arm64"
    goos: linux
    goarch: arm64
    ids:
      - boxiddi-core
docker_manifests:
  - name_template: quay.io/zebbra/s3-webhook-dumper:{{ .Tag }}
    image_templates:
      - "quay.io/zebbra/s3-webhook-dumper:{{ .Tag }}-amd64"
      - "quay.io/zebbra/s3-webhook-dumper:{{ .Tag }}-arm64"
  - name_template: quay.io/zebbra/s3-webhook-dumper:latest
    image_templates:
      - "quay.io/zebbra/s3-webhook-dumper:{{ .Tag }}-amd64"
      - "quay.io/zebbra/s3-webhook-dumper:{{ .Tag }}-arm64"
