name: build

on:
  pull_request:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - name: Build
        run: go build

      - name: Run tests
        run: go test -v ./...

